### ISSUE TITLE
Crash Game

### ISSUE THREAD

**Issue by QueenUlyana** [BoBkiNN/OpenToPublic#2]
Your mod breaks my game. The game closes with an error in the logs. 

[10:33:41] [UpnpCloseThread/ERROR]: Failed close of main port 25565
java.lang.RuntimeException: null
	at xyz.bobkinn_.opentopublic.upnp.UpnpThread.doClose(UpnpThread.java:68) ~[opentopublic-1.1-b48-R-Fabric_1.19.4.jar:?]
	at xyz.bobkinn_.opentopublic.upnp.UpnpThread.run(UpnpThread.java:23) ~[opentopublic-1.1-b48-R-Fabric_1.19.4.jar:?]
[10:33:41] [UpnpCloseThread/ERROR]: Failed to delete container file

### **Although I didn't try to open the world to a local or external network, I just played alone in my world.**

**Comment by BoBkiNN** [comment]
If this bug is still exists, please provide full logs and crash report if exists

**Comment by QueenUlyana** [comment]
> If this bug is still exists, please provide full logs and crash report if exists

It turned out that the crash was caused by the mod "Iceberg-1.19.4-fabric-1.1.10.jar". But I still don't understand why when I run my world in single player I see "[10:33:41] [UpnpCloseThread/ERROR]: Failed close of main port 25565
java.lang.RuntimeException: null
at xyz.bobkinn_.opentopublic.upnp.UpnpThread.doClose(UpnpThread.java:68) ~[opentopublic-1.1-b48-R-Fabric_1.19.4.jar:?]
at xyz.bobkinn_.opentopublic.upnp.UpnpThread.run(UpnpThread.java:23) ~[opentopublic-1.1-b48-R-Fabric_1.19.4.jar:?]
[10:33:41] [UpnpCloseThread/ERROR]: Failed to delete container file".

**Comment by BoBkiNN** [comment]
Try to manually delete .ser file in mod config folder

**Comment by QueenUlyana** [comment]
> Try to manually delete .ser file in mod config folder



> 

I don't know where it is. I have the "config" folder and the "mods" folder, but I don't have the "mod config" folder.

**Comment by BoBkiNN** [comment]
> > Try to manually delete .ser file in mod config folder
> 
> > 
> 
> I don't know where it is. I have the "config" folder and the "mods" folder, but I don't have the "mod config" folder.

This file is located in `.minecraft/config/opentopublic`/ folder
